# Generated by Django 5.2.8 on 2025-12-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
